plugins:
  container_names_enabled:
    default: false
    client: false
  main_container_name:
    default: "socket-only"
    client: "socket-only"
  data_container_name:
    default: "data"
    client: "data"
