plugins:
  container_names_enabled:
    default: false
    client: false
  main_container_name:
    default: ""
    client: ""
    hidden: true
  data_container_name:
    default: ""
    client: ""
    hidden: true
