plugins:
  container_names_enabled:
    default: false
    client: false
  main_container_name:
    default: "TBD"
    client: "TBD"
    hidden: true
  data_container_name:
    default: "TBD"
    client: "TBD"
    hidden: true
